# Header
menu:
  頭頁: /
  相輔: https://github.com/hokkien-writing

# Content
excerpt_link: 繼續閱讀

# Banner
banner: "https://hokkien-writing.github.io/banner.jpg"

# Sidebar
sidebar: right
widgets:
# - tip
- tagcloud
- recent_posts
# - category
# - qrcode
# - archive
